### ISSUE TITLE
Add LICENSE file

### ISSUE THREAD

**Issue by vazhnov** [tuupola/pico_gfx#6]
I think you've forgot to add the MIT [LICENSE](https://github.com/tuupola/pico_gfx/blob/master/LICENSE) file (but MIT license was mentioned in [README.md](https://github.com/tuupola/pico_gfx/blob/master/README.md)).

**Comment by tuupola** [comment]
Added. Thanks for the heads up!

**Comment by vazhnov** [comment]
@tuupola , thank you!
